name: flutter_flavors_template_ext
description: Base Ext Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter_flavors_demo_base_app:
    path: ../base_app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

dependency_overrides:
  flavor:
    path: flavor

# flutter:
#   uses-material-design: true
#   generate: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon-ext.png"
  min_sdk_android: 21

